
import React from 'react';
import { Helmet } from 'react-helmet';

function DisclaimerPage() {
  return (
    <>
      <Helmet>
        <title>Disclaimers | Match by Birth</title>
        <meta name="description" content="Important disclaimers about the use of our astrological compatibility calculator." />
      </Helmet>

      <main className="py-20 md:py-24 bg-background min-h-screen">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <article className="prose prose-slate dark:prose-invert prose-headings:text-balance prose-h1:text-4xl prose-h1:font-extrabold prose-a:text-primary mx-auto">
            <h1>Disclaimers</h1>
            
            <h2>Astrology Disclaimer</h2>
            <p>
              Match by Birth is a tool created for <strong>entertainment purposes only</strong>. The compatibility scores, group vibe percentages, and descriptive texts generated by our site are based on traditional Western astrological archetypes. Astrology is a symbolic language and not a rigorous science.
            </p>

            <h2>Not Professional Advice</h2>
            <p>
              The results provided by our calculator should never be interpreted as psychological, relationship, medical, legal, or financial advice. If you are facing significant relationship challenges, mental health issues, or need professional guidance, we strongly encourage you to consult with a licensed therapist, counselor, or appropriate professional.
            </p>

            <h2>Accuracy and Methodology</h2>
            <p>
              While we use standard astrological rules to calculate sun signs, elements, and modalities, the concept of "zodiac compatibility" is highly subjective and has not been scientifically proven. Human personalities are incredibly complex and cannot be fully summarized by a birth date alone.
            </p>

            <h2>No Guarantees</h2>
            <p>
              A high matching percentage on our site does not guarantee relationship success, perfect chemistry, or an absence of conflict. Conversely, a low score does not mean a relationship is doomed to fail. The most successful relationships are built on mutual respect, ongoing communication, empathy, and active effort—none of which can be measured by a calculator. 
            </p>
            <p>
              By using Match by Birth, you acknowledge that you are fully responsible for your own life choices and actions, and that you will not use our platform's outputs to make serious life decisions.
            </p>
          </article>
        </div>
      </main>
    </>
  );
}

export default DisclaimerPage;
