
import React from 'react';
import { Helmet } from 'react-helmet';
import BackButton from '@/components/BackButton.jsx';

function DisclaimerPage() {
  return (
    <>
      <Helmet>
        <title>Disclaimers | Match by Birth</title>
        <meta name="description" content="Important disclaimers about the use of our astrological compatibility calculator." />
        <link rel="canonical" href="https://matchbybirth.com/disclaimers" />
      </Helmet>

      <main className="py-16 md:py-24 bg-background min-h-screen relative overflow-hidden">
        {/* Decorative background gradients */}
        <div className="pointer-events-none absolute top-0 right-1/4 h-[300px] w-[300px] rounded-full opacity-[0.07] blur-3xl bg-primary" />
        
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <BackButton fallbackTo="/" label="Back to Calculator" />
          
          <div className="bg-card border border-border rounded-3xl p-8 md:p-12 shadow-sm shadow-elevated">
            <header className="mb-10 border-b border-border pb-6">
              <h1 className="text-3xl md:text-4xl font-bold text-foreground tracking-tight">Disclaimers</h1>
              <p className="text-sm text-muted-foreground mt-2">Important information about using our compatibility calculator.</p>
            </header>

            <section className="space-y-8">
              <div>
                <h2 className="text-xl md:text-2xl font-semibold text-foreground mb-3">Astrology Disclaimer</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Match by Birth is a tool created for <strong className="text-foreground font-semibold">entertainment purposes only</strong>. The compatibility scores, group vibe percentages, and descriptive texts generated by our site are based on traditional Western astrological archetypes. Astrology is a symbolic language and not a rigorous science.
                </p>
              </div>

              <div>
                <h2 className="text-xl md:text-2xl font-semibold text-foreground mb-3">Not Professional Advice</h2>
                <p className="text-muted-foreground leading-relaxed">
                  The results provided by our calculator should never be interpreted as psychological, relationship, medical, legal, or financial advice. If you are facing significant relationship challenges, mental health issues, or need professional guidance, we strongly encourage you to consult with a licensed therapist, counselor, or appropriate professional.
                </p>
              </div>

              <div>
                <h2 className="text-xl md:text-2xl font-semibold text-foreground mb-3">Accuracy and Methodology</h2>
                <p className="text-muted-foreground leading-relaxed">
                  While we use standard astrological rules to calculate sun signs, elements, and modalities, the concept of &quot;zodiac compatibility&quot; is highly subjective and has not been scientifically proven. Human personalities are incredibly complex and cannot be fully summarized by a birth date alone.
                </p>
              </div>

              <div>
                <h2 className="text-xl md:text-2xl font-semibold text-foreground mb-3">No Guarantees</h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  A high matching percentage on our site does not guarantee relationship success, perfect chemistry, or an absence of conflict. Conversely, a low score does not mean a relationship is doomed to fail. The most successful relationships are built on mutual respect, ongoing communication, empathy, and active effort—none of which can be measured by a calculator. 
                </p>
                <p className="text-muted-foreground leading-relaxed">
                  By using Match by Birth, you acknowledge that you are fully responsible for your own life choices and actions, and that you will not use our platform&apos;s outputs to make serious life decisions.
                </p>
              </div>
            </section>
          </div>
        </div>
      </main>
    </>
  );
}

export default DisclaimerPage;
