
import React from 'react';
import { Helmet } from 'react-helmet';

function TermsOfServicePage() {
  return (
    <>
      <Helmet>
        <title>Terms of Service | Match by Birth</title>
        <meta name="description" content="Terms of Service for using Match by Birth." />
      </Helmet>

      <main className="py-20 md:py-24 bg-background min-h-screen">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <article className="prose prose-slate dark:prose-invert prose-headings:text-balance prose-h1:text-4xl prose-h1:font-extrabold prose-a:text-primary mx-auto">
            <h1>Terms of Service</h1>
            <p className="text-sm font-medium uppercase tracking-wider text-muted-foreground mb-8">
              Last Updated: June 9, 2026
            </p>

            <h2>1. Welcome to Match by Birth</h2>
            <p>
              By accessing and using Match by Birth, you agree to follow these Terms of Service. If you don't agree with them, please refrain from using the site.
            </p>

            <h2>2. Astrology Disclaimer</h2>
            <p>
              All compatibility scores, group vibe percentages, and astrological interpretations provided on this site are for <strong>entertainment purposes only</strong>. Astrology is a symbolic system, not an empirical science. Our results should never be used as the basis for major life decisions, relationship choices, or professional advice.
            </p>

            <h2>3. Group Mode & Functionality</h2>
            <p>
              Match by Birth offers a "Group Mode" that allows users to calculate the compatibility of up to 7 individuals simultaneously. The calculator computes the scores of all possible pairings to generate a "Group Vibe Score." You agree to only input names and birth dates of individuals you have permission to analyze or whose information is reasonably public within your social circle.
            </p>

            <h2>4. Sharing and URLs</h2>
            <p>
              Shared results use an opaque link that displays the sanitized names, signs, scores, and interpretations associated with that result. Birth dates are not included in new sharing URLs. Anyone with the link can view the result, so you are responsible for sharing it appropriately.
            </p>

            <h2>5. Data Handling</h2>
            <p>
              Birth dates are processed transiently and are not stored. Sanitized result data, purchase records, reports, and consented email subscriptions may be stored as described in our Privacy Policy.
            </p>

            <h2>6. Third-Party Advertising (AdSense)</h2>
            <p>
              We use third-party advertising partners, including Google AdSense, to display ads on our website. These partners may use cookies and similar tracking technologies to serve ads based on your prior visits to our site and other sites on the internet.
            </p>

            <h2>7. User Responsibility</h2>
            <p>
              You agree to use Match by Birth responsibly and lawfully. You will not use the service to harass, stalk, or mock others. We provide the tool; how you communicate the results to your friends or partners is entirely up to you.
            </p>

            <h2>8. No Warranty</h2>
            <p>
              Match by Birth is provided "as is" and "as available." We make no guarantees about the accuracy, reliability, or uninterrupted availability of the calculator.
            </p>

            <h2>9. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Match by Birth and its operators shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your use of the site or your reliance on any compatibility scores or readings generated by it.
            </p>
          </article>
        </div>
      </main>
    </>
  );
}

export default TermsOfServicePage;
