export const REPORT_FOCUS_CONFIG = {
  moon_sign: {
    label: 'Moon Sign Match Report',
    shortLabel: 'Moon report',
    eyebrow: 'Full Moon Sign report',
    title: 'See what care and repair look like for both of you',
    summary: 'A private nine-section report about emotional needs, common misreads, reassurance, and repair.',
    previewTitle: 'Moon Sign report preview',
    previewHeading: 'Your emotional pattern',
    previewCopy: 'The report compares both calculated Moon signs, shows where care can miss, and gives you words for reassurance or repair.',
    detail: 'Includes both Moon signs, emotional needs, the likely misread, a repair script, and a seven-day reality check.',
    button: 'Buy the Moon report for $9.99',
    resultHeadline: 'See how emotional needs, conflict, and repair fit together.',
    resultPreview: 'The paid Moon report turns both Moon signs and the emotional score into specific situations, repair language, and a seven-day check.',
    includes: [
      'Both calculated Moon signs and precision note',
      'How care and reassurance can be misread',
      'A conflict and repair pattern to watch',
      'Words to use plus a seven-day check',
    ],
    clarityPrompt: 'What do you want the report to help with?',
    defaultClarityGoal: 'repair_after_conflict',
    clarityGoals: [
      ['repair_after_conflict', 'Repair after conflict'],
      ['reassurance', 'Giving reassurance'],
      ['emotional_distance', 'Emotional distance'],
    ],
    features: [
      ['heart', 'What care feels like', 'How each Moon sign tends to recognize reassurance and support.'],
      ['alert', 'The misread to catch', 'Where two emotional styles can assign different meanings to the same moment.'],
      ['message', 'A repair script', 'Direct words for checking intent, asking for space, or returning to a hard topic.'],
      ['compass', 'A seven-day check', 'A small way to compare the reading with what actually happens.'],
    ],
  },
  crush: {
    label: 'Crush Compatibility Report',
    shortLabel: 'Crush report',
    eyebrow: 'Full Crush Compatibility report',
    title: 'Separate chemistry from real signs of interest',
    summary: 'A private nine-section report about attraction, mixed signals, consistency, pace, and what to do next.',
    previewTitle: 'Crush report preview',
    previewHeading: 'What creates the pull',
    previewCopy: 'The report compares chemistry with communication and consistency, then gives you a low-pressure next move.',
    detail: 'Includes attraction signals, mixed-signal checks, consistency, an investment watch, a message to send, and a seven-day evidence check.',
    button: 'Buy the Crush report for $9.99',
    resultHeadline: 'See whether the pull is supported by clarity and follow-through.',
    resultPreview: 'The paid Crush report separates chemistry from consistency and turns the score into one clear, low-pressure next move.',
    includes: [
      'Chemistry compared with communication',
      'Mixed signals and signs of real effort',
      'What not to over-invest in',
      'A message to send plus a seven-day check',
    ],
    clarityPrompt: 'What do you want clarity on?',
    defaultClarityGoal: 'mixed_signals',
    clarityGoals: [
      ['mixed_signals', 'Mixed signals'],
      ['pace', 'The right pace'],
      ['next_move', 'What to do next'],
    ],
    features: [
      ['heart', 'What creates the pull', 'How chemistry and the two birth-sign styles contribute to the result.'],
      ['alert', 'Mixed signals', 'How to separate a hopeful interpretation from repeated effort.'],
      ['message', 'A message you can send', 'One direct line that creates clarity without adding pressure.'],
      ['compass', 'A seven-day evidence check', 'What to watch before investing more time or emotion.'],
    ],
  },
  life_path: {
    label: 'Life Path Compatibility Report',
    shortLabel: 'Life Path report',
    eyebrow: 'Full Life Path report',
    title: 'See how effort, goals, and responsibility fit together',
    summary: 'A private nine-section report about drive, support, decisions, shared goals, and long-term fit.',
    previewTitle: 'Life Path report preview',
    previewHeading: 'How each of you moves through life',
    previewCopy: 'The report compares both Life Path numbers, shows where effort can be misread, and gives you a thirty-day compatibility test.',
    detail: 'Includes both Life Path numbers, effort styles, shared direction, responsibility, a planning script, and a thirty-day test.',
    button: 'Buy the Life Path report for $9.99',
    resultHeadline: 'See how your priorities work when a real decision has to be made.',
    resultPreview: 'The paid Life Path report turns both numbers into a practical look at effort, decisions, responsibility, and long-term fit.',
    includes: [
      'Both calculated Life Path numbers',
      'How effort and support can differ',
      'Shared goals and divided responsibility',
      'A planning script plus a thirty-day test',
    ],
    clarityPrompt: 'What should the report focus on?',
    defaultClarityGoal: 'long_term_fit',
    clarityGoals: [
      ['long_term_fit', 'Long-term fit'],
      ['shared_goals', 'Shared goals'],
      ['responsibility', 'Responsibility'],
    ],
    features: [
      ['compass', 'Direction and priorities', 'How both Life Path themes shape goals, pace, and decisions.'],
      ['heart', 'Effort and support', 'What each person may offer and what the other may actually need.'],
      ['alert', 'The responsibility watch', 'Where planning, control, or uneven follow-through can create resentment.'],
      ['message', 'A thirty-day test', 'A shared goal, a planning script, and a clear date to review what happened.'],
    ],
  },
  full_compatibility: {
    label: 'Full Compatibility Report',
    shortLabel: 'full report',
    eyebrow: 'Full Compatibility report',
    title: 'Turn the score into a real conversation',
    summary: 'A private nine-section report about the strongest area, the repeating risk, emotional pace, reliability, and repair.',
    previewTitle: 'Full report preview',
    previewHeading: 'The pattern underneath the score',
    previewCopy: 'The report connects all five score areas with emotional pace, ordinary follow-through, and a usable repair plan.',
    detail: 'Includes the full score spread, emotional pace, reliability, the repeating watch pattern, repair words, and a seven-day plan.',
    button: 'Buy the full report for $9.99',
    resultHeadline: 'See how the strongest score and watch area show up together.',
    resultPreview: 'The paid report connects the full score spread to real conversations, follow-through, emotional pace, and repair.',
    includes: [
      'All five compatibility dimensions',
      'The strongest asset and repeating risk',
      'Emotional pace and reliability',
      'Repair words plus a seven-day plan',
    ],
    clarityPrompt: 'What should the report focus on?',
    defaultClarityGoal: 'communication',
    clarityGoals: [
      ['communication', 'Communication'],
      ['conflict', 'Conflict'],
      ['long_term_fit', 'Long-term fit'],
    ],
    features: [
      ['message', 'How conversations cross', 'Where different pace, tone, or expectations can create a wrong read.'],
      ['heart', 'The strongest asset', 'The measured area that is easiest to turn into a repeatable behavior.'],
      ['alert', 'The repeating risk', 'The lowest score area and the ordinary situation where it may matter.'],
      ['compass', 'A seven-day plan', 'Specific words and behaviors to compare with real life.'],
    ],
  },
};

export function getReportFocusConfig(value) {
  return REPORT_FOCUS_CONFIG[value] || REPORT_FOCUS_CONFIG.full_compatibility;
}
